version: "3"

services:
  front:
    image: front
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - back
  back:
    image: back
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - database
  database:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
networks:
  app-network:
